name: "Build"

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"

defaults:
  run:
    shell: bash

env:
  SERVER_IMAGE: "quay.io/fmperf/fmperf"
  IMAGE_REGISTRY: "quay.io"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v3

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Log in to container registry (server-release)"
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ secrets.FMPERF_QUAY_USER }}
          password: ${{ secrets.FMPERF_QUAY_TOKEN }}

      - name: "List docker images"
        run: docker images

      - name: "Check disk usage"
        shell: bash
        run: |
          docker system df
          df -h
