name: Kind cluster CI
on:
  - push
  - pull_request
jobs:
  create-kind-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.11.1
          config: kind-gpu.yaml
      - name: Verify Cluster
        run: kubectl cluster-info
