name: Kind Cluster Setup

on: [push, pull_request]

jobs:
  create-cluster:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Kind
      uses: engineerd/setup-kind@v0.5.0
      with:
        version: 'v0.11.1'  # Use the latest version of Kind

    - name: Create Kind Cluster
      run: |
        kind create cluster --config kind-gpu.yaml
        # Extract and print the cluster name
        cluster_name=$(grep '^name:' kind-gpu.yaml | sed 's/name: //')
        echo "Cluster name: $cluster_name"
      shell: bash

    - name: Verify Cluster
      run: |
        kubectl cluster-info
      shell: bash
